# Site settings
title: Sanghack Lee 이상학
email: sanghack.lee@gmail.com
description: > #Sanghack Lee curriculum vitae or resume
baseurl: ""
url: "http://sanghacklee.me"
name: Sanghack Lee
job: Assistant Professor
location: Seoul, Republic of Korea
#languages: HTML, CSS and Javascript
#twitter_username: sanghack81
github_username:  sanghack81
email_address: sanghack.lee@gmail.com
linkedin_username: sanghack-lee-65b52a28
# Build settings
markdown: kramdown
